# Generated by Django 3.2.2 on 2023-07-31 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20230731_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='id',
        ),
        migrations.AlterField(
            model_name='info',
            name='email',
            field=models.CharField(max_length=30, primary_key=True, serialize=False),
        ),
    ]
