# Generated by Django 3.2.2 on 2023-08-02 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='img',
        ),
        migrations.RemoveField(
            model_name='image',
            name='name',
        ),
        migrations.AddField(
            model_name='image',
            name='vid',
            field=models.ImageField(default=None, upload_to='videos/'),
        ),
        migrations.AddField(
            model_name='info',
            name='array_id',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
