# Generated by Django 3.2.2 on 2023-08-02 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20230802_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='vid',
            field=models.FileField(default=None, upload_to='videos/'),
        ),
    ]
