# Generated by Django 3.2.2 on 2023-08-04 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20230802_1501'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='array_id',
            new_name='img_id',
        ),
        migrations.AddField(
            model_name='info',
            name='vid_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
